apiVersion: batch/v1
kind: Job
metadata:
  name: populate-content
spec:
  template:
    spec:
      containers:
        - name: writer
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - echo "Hello from NFS!" > /mnt/index.html;
          volumeMounts:
            - name: nfs-volume
              mountPath: /mnt
      restartPolicy: OnFailure
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
